name: "Build & Release"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: debug
    runs-on: debian-latest

steps:
  - name: Clone repository
    uses: actions/checkout@v4
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable # or: beta, master (or main)
  - run: flutter pub get
  - run: flutter test
  - run: flutter build apk
  - run: flutter build appbundle
  - name: Upload Artifacts
    uses: actions/upload-artifact@v4.6.1
    with:
      name: Releases
      path: |
        build/app/outputs/flutter-apk/app-release.apk
        build/app/outputs/bundle/release/app-release.aab
        build/ios_build.tar.g
        
